language: java

jdk:
  - openjdk14

services:
  - postgresql

before_install:
  - psql -c 'create database dreamjob;' -U postgres

sudo: false

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:

    on_success: never # default: change
    on_failure: always # default: always

env:
  global:
    - CODECOV_TOKEN="50519f90-4bbd-4496-9e4c-9fd908d02eca"